### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by liuyuyuil** [ShuhongChen/eisai-anime-interpolator#1]
Thanks for your great work ! Do you guys have any plans for releasing the code ? Thanks!

**Comment by ShuhongChen** [comment]
Thanks for your interest in our work; yes, the paper's still under review now but if it's accepted we plan to release code

**Comment by styler00dollar** [comment]
It seems like ECCV2022 got added to the readme. Does this mean that the code will release soon? If yes, can I have an estimate? I am very curious about the dataset generation code and the model itself.

**Comment by ShuhongChen** [comment]
Thanks for your patience; yes, we're prepping the code now.  I'm aiming to finish this by next weekend; my hard deadline is the camera-ready on 07/20, which requires code url

> curious about the dataset generation code and the model itself

I'll try to make this as painless as possible; it's currently spread across 4+ private repos...
