### ISSUE TITLE
could you please write a image sequence deduplicate alone?

### ISSUE THREAD

**Issue by routineLife1** [ShuhongChen/eisai-anime-interpolator#10]
I'm very interested in your frames deduplication, but the code doesn't seem to be practical
so, could you please write a image sequence deduplicate alone usage similar to [this](https://github.com/YiWeiHuang-stack/AVFDU/blob/main/flow.py)

**Comment by ShuhongChen** [comment]
> the code doesn't seem to be practical

Could you clarify this; do you mean speed, or space, or user experience?  The algorithm is relatively simple, please see the other [issue](https://github.com/ShuhongChen/eisai-anime-interpolator/issues/4#issuecomment-1189751323) for some details and pointers to code

**Comment by routineLife1** [comment]
oh，sorry，i mean the  user experience

**Comment by ShuhongChen** [comment]
> i mean the user experience

Oh, sorry; we don't really have time to improve UX, though if you have questions about the process please ask

If you write a better UX script, feel free to open a PR

**Comment by routineLife1** [comment]
使用rrld data pipeline创建数据集时，发现创建的数据集几乎全为平移场景，好不容易见到个人物动的，却是一拍二，意思是这个除重复帧只除去的是完全重复么，以及我发现筛选出来的数据大部分都是同一个场景，需要我自己找个转场识别来分开嘛

用别的方法除了下一拍三，ffmpeg叠重复帧到23.976，再扔到rrld data pipeline里确实筛出来点人物动的帧了

筛出来的一部分三帧组看上去挺不错

![imageonline-co-gifimage (1)](https://user-images.githubusercontent.com/68835291/184395034-ab351cc0-3d95-4a01-9f0d-e013412e19d4.gif)


但也有一部分看上去不是很线性

![imageonline-co-gifimage](https://user-images.githubusercontent.com/68835291/184393796-e0d44ea3-9510-4415-9e44-77dd806327f0.gif)

**Comment by ShuhongChen** [comment]
> 发现创建的数据集几乎全为平移场景

这比较奇怪，我们专门把[pan拿掉](https://github.com/ShuhongChen/eisai-anime-interpolator/blob/29f50de172188a871bff4d01453cd2252d4c64b9/_scripts/rrld_filter.py#L118)

我没有完全看懂你说的关于ffmpeg，但我估计是deduplication的问题（做rrld时是不能有重复帧）；我们选的deduplicator parameters是按照从bluray来的帧，要是你的video quality没有我们那么好，重复帧之间的差别跟大，可能deduplicator以为不是重复？

我们实验里平均50%被label成重复帧，如你的DatabaseVideoFrameDuplicates少于45%可能会出问题；可以纠正一些[parameters](https://github.com/ShuhongChen/eisai-anime-interpolator/blob/29f50de172188a871bff4d01453cd2252d4c64b9/_util/frames_v0.py#L14)

> 大部分都是同一个场景，需要我自己找个转场识别来分开嘛

这是很有可能；我们用的是[transnet v2](https://github.com/soCzech/TransNetV2)，他们repo很好用

**Comment by routineLife1** [comment]
噢，我一开始是没有用ffmpeg去处理视频的，直接跑rrld pipeline筛选出来的三帧组平移很多，人物动作也几乎筛不出来，即使筛出来人物运动，很多时候也是一看就是非线性的，所以我推测rrld pipeline里的deduplication是只能除去完全重复帧
所以我用其他的方法从一拍N中选择一帧，组成一拍一的视频，用ffmpeg叠完全重复帧到23.976，再送到rrld pipe line里跑，结果会好很多

这视频估计是没有任何帧被标记为重复帧，我也试了其他的动漫视频(vcb-s的源)，结果也是一样的，会不会是在整理rrld pipeline代码时有失误？以及我前几天试着摘掉DTM，看了很多的数据，发现带不带DTM完全没有任何区别，ssim 对比出来的值也极限接近与1，会不会是DTM的代码在整理时出现了问题
另外我认为制作三帧组数据集不需要很精确的转场识别，其实直接cv2.absdiff(a,b).mean() > 40就够用

晚一些试试改parameters

**Comment by ShuhongChen** [comment]
啊，要是我没记错 RRLD 里面用的 DALI 比较严格，前面 ffmpeg 的一步应该很重要

看来是 dedup 的问题，估计是因为 video quality 不同；要是你有大量数据，该 parameter 可能不如跳一帧跳一帧地做 dedup；简单很多，说不定结果差不多

你说的关于 DTM 我没看懂；DTM 是网络里的一部分，跟 RRLD data extraction 无关？

**Comment by routineLife1** [comment]
DALI已经是经过人工筛选的了，只剩下了一拍一画面，筛选起来比较容易
是，DTM是另外的一个话题（
我发现DTM在任何数据上均没有起到作用，会不会源代码哪里出现了问题？
带dtm或去掉dtm，生成的结果用ssim对比出来的值极限接近与1

**Comment by ShuhongChen** [comment]
> 我发现DTM在任何数据上均没有起到作用

这是有可能，如果看我们paper里的table2，DTM在动漫上的进步确实比较小；好多都像figure4第二排

**Comment by routineLife1** [comment]
不，我是觉得他运行的可能有问题，网络是正常在跑，但是结果一点区别都没有，论文中至少是有效果的。

**Comment by ShuhongChen** [comment]
你能重现[evaluation](https://github.com/ShuhongChen/eisai-anime-interpolator#evaluation)里面的数字吗？如果数字匹配那运行应该没有问题

**Comment by chenjjcccc** [comment]
> 使用rrld data pipeline创建数据集时，发现创建的数据集几乎全为平移场景，好不容易见到个人物动的，却是一拍二，意思是这个除重复帧只除去的是完全重复么，以及我发现筛选出来的数据大部分都是同一个场景，需要我自己找个转场识别来分开嘛
> 
> 用别的方法除了下一拍三，ffmpeg叠重复帧到23.976，再扔到rrld data pipeline里确实筛出来点人物动的帧了
> 
> 筛出来的一部分三帧组看上去挺不错
> 
> ![imageonline-co-gifimage (1)](https://user-images.githubusercontent.com/68835291/184395034-ab351cc0-3d95-4a01-9f0d-e013412e19d4.gif) [ ![imageonline-co-gifimage (1)](https://user-images.githubusercontent.com/68835291/184395034-ab351cc0-3d95-4a01-9f0d-e013412e19d4.gif) ](https://user-images.githubusercontent.com/68835291/184395034-ab351cc0-3d95-4a01-9f0d-e013412e19d4.gif) [ ](https://user-images.githubusercontent.com/68835291/184395034-ab351cc0-3d95-4a01-9f0d-e013412e19d4.gif)
> 
> 但也有一部分看上去不是很线性
> 
> ![imageonline-co-gifimage](https://user-images.githubusercontent.com/68835291/184393796-e0d44ea3-9510-4415-9e44-77dd806327f0.gif) [ ![imageonline-co-gifimage](https://user-images.githubusercontent.com/68835291/184393796-e0d44ea3-9510-4415-9e44-77dd806327f0.gif) ](https://user-images.githubusercontent.com/68835291/184393796-e0d44ea3-9510-4415-9e44-77dd806327f0.gif) [ ](https://user-images.githubusercontent.com/68835291/184393796-e0d44ea3-9510-4415-9e44-77dd806327f0.gif)

你好，请问能上传一下用rrld生成的数据集吗
