### ISSUE TITLE
google colab request

### ISSUE THREAD

**Issue by mikebilly** [ShuhongChen/eisai-anime-interpolator#12]
this project looks very promising, I think it would be nice to have a google colab notebook for people to try out what this AI could do

**Comment by ShuhongChen** [comment]
Thanks for the suggestion; I'll maybe try to find some time this weekend

**Comment by mikebilly** [comment]
Great! I suggest that you should make it fully utilize google colab's free GPU for maximum interpolation speed

**Comment by ShuhongChen** [comment]
https://github.com/ShuhongChen/eisai-anime-interpolator#colab-demo
