### ISSUE TITLE
请问数据集可以公布吗？

### ISSUE THREAD

**Issue by chenjjcccc** [ShuhongChen/eisai-anime-interpolator#15]

**Comment by routineLife1** [comment]
有版权问题吧

**Comment by chenjjcccc** [comment]
请问你实现rrld数据集时，在运行encoding时，利用ffmpeg编码时，会出现部分参数无效的现象吗？我在执行过程中出现了错误，例如：



我找了很久也没有找到好的解决办法，想向您请教一下。




#·俊·#--
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShuhongChen/eisai-anime-interpolator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月14日(星期六) 中午12:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ShuhongChen/eisai-anime-interpolator] 请问数据集可以公布吗？ (Issue #15)





 
有版权问题吧

**Comment by chenjjcccc** [comment]
顺便问一下你使用的ffmpeg的版本是多少呢&nbsp;




#·俊·#--
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShuhongChen/eisai-anime-interpolator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月14日(星期六) 中午12:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ShuhongChen/eisai-anime-interpolator] 请问数据集可以公布吗？ (Issue #15)





 
有版权问题吧

**Comment by ShuhongChen** [comment]
> 有版权问题吧

是的，不好意思我们没法公布

> 我在执行过程中出现了错误，例如

如果用docker里的ffmpeg因该没问题

> 使用的ffmpeg的版本是多少呢

docker里的:

    /usr/bin/ffmpeg -version
    ffmpeg version 3.4.11-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
    built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
    configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
    libavutil      55. 78.100 / 55. 78.100
    libavcodec     57.107.100 / 57.107.100
    libavformat    57. 83.100 / 57. 83.100
    libavdevice    57. 10.100 / 57. 10.100
    libavfilter     6.107.100 /  6.107.100
    libavresample   3.  7.  0 /  3.  7.  0
    libswscale      4.  8.100 /  4.  8.100
    libswresample   2.  9.100 /  2.  9.100
    libpostproc    54.  7.100 / 54.  7.100
