### ISSUE TITLE
ffmpeg部分参数无法识别

### ISSUE THREAD

**Issue by chenjjcccc** [ShuhongChen/eisai-anime-interpolator#17]
![image](https://user-images.githubusercontent.com/95216119/212469691-a9cbdf30-d48a-4ea2-87c8-ea704bfa1ab2.png)

**Comment by chenjjcccc** [comment]
请问ffmpeg的版本是多少呢

**Comment by ShuhongChen** [comment]
https://github.com/ShuhongChen/eisai-anime-interpolator/issues/15#issuecomment-1382883610

**Comment by chenjjcccc** [comment]
谢谢，但是我使用ffmpeg任然会报错，识别不了参数rc、qp等等
![image](https://user-images.githubusercontent.com/95216119/212528518-41c444d5-396d-4b46-9170-e7a7ed5d176b.png)

**Comment by chenjjcccc** [comment]
> 谢谢，但是我使用ffmpeg任然会报错，识别不了参数rc、qp等等 ![image](https://user-images.githubusercontent.com/95216119/212528518-41c444d5-396d-4b46-9170-e7a7ed5d176b.png)

请问您有遇到类似的问题吗

**Comment by ShuhongChen** [comment]
这我从没遇到过；您用的是docker里的？我昨天docker里从试了一下，没问题

**Comment by chenjjcccc** [comment]
> 这我从没遇到过；您用的是docker里的？我昨天docker里从试了一下，没问题

是的，就是没有参数-rc 我在上网好像也查询不到这个参数，我试过了很多个版本的ffmpeg，都存在这个问题

**Comment by chenjjcccc** [comment]
> > 这我从没遇到过；您用的是docker里的？我昨天docker里从试了一下，没问题
> 
> 是的，就是没有参数-rc 我在上网好像也查询不到这个参数，我试过了很多个版本的ffmpeg，都存在这个问题
请问-rc这个参数是什么意思呢，或者您能打包您的ffmpeg并且公布出来吗

**Comment by ShuhongChen** [comment]
您用的docker image是从docker pull还是自己docker build？如是build的话是有这可能性，用pull不因该有问题

**Comment by chenjjcccc** [comment]
> 您用的docker image是从docker pull还是自己docker build？如是build的话是有这可能性，用pull不因该有问题

我在使用docker_pull后，执行shell_docker时出现了 不能load libnvidia-ml.so.1文件，请问是否是镜像变动导致的呢？

**Comment by ShuhongChen** [comment]
我没完全了解，您是说shell_docker根本进不去image？
