### ISSUE TITLE
docker question

### ISSUE THREAD

**Issue by suchuankai** [ShuhongChen/eisai-anime-interpolator#18]
Sorry, I am a beginner using docker,
After pull docker image and enter container, 
I run the command "bash ./_scripts/rrld_pipeline.sh ./video.mp4 ./temp/rrld_demo_output"
and got 2 errors,

First is  " Cannot load libcuda.so.1"
I try to add LD_LIBRARY_PATH but it still didn't work.

And the second is 
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

I search a lot but still can't solve these two errors.

Please let me know if you know what the problem might be.

Thank you very much!

![image](https://user-images.githubusercontent.com/69788052/212556410-fea41c67-402c-4ec3-8a7e-1e71015f0423.png)

**Comment by ShuhongChen** [comment]
Hello, does your computer have a nvidia gpu? i.e. does `nvidia-smi` work in the docker container?

**Comment by suchuankai** [comment]
When working in the docker container,  it doesn't work.
But work outside container.

Outside:
![image](https://user-images.githubusercontent.com/69788052/212652017-5a7906a8-2c65-4266-a4d1-e35178978ce5.png)

In:
![image](https://user-images.githubusercontent.com/69788052/212652116-ad1d61f1-950f-4db7-8eea-ef36ad2cdd9c.png)

**Comment by suchuankai** [comment]
Thank you!
After adding --gpus all , I solve this problem!!

Now I face 

Error when executing GPU operator readers__VideoResize encountered:
CUDA allocation failed
Current pipeline object is no longer valid.

I think this is because cuda out of memory, I'm still trying it.
Thank you very much!

**Comment by chenjjcccc** [comment]
> Thank you! After adding --gpus all , I solve this problem!!
> 
> Now I face
> 
> Error when executing GPU operator readers__VideoResize encountered: CUDA allocation failed Current pipeline object is no longer valid.
> 
> I think this is because cuda out of memory, I'm still trying it. Thank you very much!

What version of docker are you using? When I use shell_docker,A file not found error occurs

**Comment by chenjjcccc** [comment]
What version of docker are you using? When I use shell_docker,A file not found error occurs

**Comment by ShuhongChen** [comment]
> After adding --gpus all , I solve this problem!!

Are you using the shell scripts provided in the make folder; you should use these instead of entering the docker container by yourself.  The commands in the instructions should've taken care of all the docker flags for you; for example `--gpus all` is already [here](https://github.com/ShuhongChen/eisai-anime-interpolator/blob/c2478f0d7ce6a8a60d2b8332520265b4317055a6/_env/make_config.bashrc#L14)

> What version of docker are you using

    docker --version
    Docker version 20.10.2, build 2291f61

> When I use shell_docker,A file not found error occurs

Which file isn't found

**Comment by suchuankai** [comment]
Yes, I pull the image and entering the docker container by myself.
Because when I run "make/shell_docker"
I got error  :  

`  docker: invalid reference format: repository name must be lowercase.   ` 

I think there are some errors in my file "machine_config.bashrc", 

I just modify PROJECT_DN and  MOUNTS_DOCKER, I'm not sure how to fill in.

I use wsl2 on win11.

Sorry for taking your time.

![image](https://user-images.githubusercontent.com/69788052/212887000-e9aaed1e-2eee-449c-9c44-de2c0cc56565.png)

**Comment by ShuhongChen** [comment]
>  docker: invalid reference format: repository name must be lowercase.  

This is strange, this shouldn't happen unless you changed `project_config.bashrc`.  I recommend double checking `project_config` isn't changed, and redoing the docker pull script

> I use wsl2 on win11. ... I'm not sure how to fill in.

I'm unfamiliar with how to do this on wsl, but my recommendation for `PROJECT_DN` is the path within wsl; i.e. you should set it such that `cd $PROJECT_DN` within wsl terminal, and get to the folder

Also set `MOUNTS_DOCKER` empty, it shouldn't apply to most people

**Comment by suchuankai** [comment]
Thanks for your help. 
After converting the operating system to Linux instead of WSL, I was able to successfully run the program. 
But I have one question I would like to ask for your guidance. 
Could you tell me which part in the code is the implementation of infill? 
I noticed in interpolator_v0.py that is_flow is set to false. Does that mean  infill has already been performed in logimgs in the class Synthesizer? 
Thank you very much !!!

**Comment by ShuhongChen** [comment]
Good to hear you got it working

> which part in the code is the implementation of infill?

https://github.com/ShuhongChen/eisai-anime-interpolator/blob/c2478f0d7ce6a8a60d2b8332520265b4317055a6/_train/frame_interpolation/models/ssldtm.py#L130

> interpolator_v0.py that is_flow is set to false

This is unrelated; resizing flows requires rescaling flow values
