### ISSUE TITLE
some question about evaluate

### ISSUE THREAD

**Issue by ll-yhlf** [ShuhongChen/eisai-anime-interpolator#19]
when I run this commend: python3 -m _scripts.evaluate, the program encountered the following error.How should I solve this problem?
![image](https://user-images.githubusercontent.com/67399915/223306614-654fd625-4619-43e8-aaa2-6b7f37cee090.png)

**Comment by ShuhongChen** [comment]
full stack trace please

**Comment by ll-yhlf** [comment]
I'm sorry to bother you, I found that I made a wrong version of torchvision.

**Comment by ShuhongChen** [comment]
Ok, no problem

**Comment by ll-yhlf** [comment]
another question：how can I use myself checkpoints I trained to get the evaluation results. It means that ssl.pt and dtm.pt are not used
