### ISSUE TITLE
"Could you kindly provide the code for filtering ATD-12k with RRLD? It appears that the currently available RRLD code only can generate new triplets using RRLD~

### ISSUE THREAD

**Issue by kimwao** [ShuhongChen/eisai-anime-interpolator#20]

**Comment by ShuhongChen** [comment]
The pipeline actually is broken into different steps with different scripts in the `_scripts` folder; if you want to use the RRLD filter on other data like ATD12k, you can follow this line in the pipeline [here](https://github.com/ShuhongChen/eisai-anime-interpolator/blob/c2478f0d7ce6a8a60d2b8332520265b4317055a6/_scripts/rrld_pipeline.sh#L15)
