### ISSUE TITLE
cv2.optflow.createOptFlow_DualTVL1()

### ISSUE THREAD

**Issue by luyiwen-user** [ShuhongChen/eisai-anime-interpolator#21]
当我运行python3 -m _scripts.evaluate时，报错如下，而且我在查询cv2包中并没有这个函数cv2.optflow.createOptFlow_DualTVL1()
<img width="671" alt="image" src="https://github.com/ShuhongChen/eisai-anime-interpolator/assets/81129278/63ae17ab-765f-4fe9-9f66-9474b1420e9e">

**Comment by luyiwen-user** [comment]
> 当我运行python3 -m _scripts.evaluate时，报错如下，而且我查询发现cv2包中并没有这个函数cv2.optflow.createOptFlow_DualTVL1() <img alt="image" width="671" src="https://user-images.githubusercontent.com/81129278/252965406-63ae17ab-765f-4fe9-9f66-9474b1420e9e.png">

**Comment by ShuhongChen** [comment]
你是在docker container里吗？估计是因为有不同cv2 version，请用dockerfile里的version试一试

好像这行是以前用来做比较的，删了也应该对eval没影响

**Comment by luyiwen-user** [comment]
很抱歉再次打扰您，我是一个dockers新手，在ubuntu安装doucker后，运行`make/docker_pull`命令时，发生下列报错：
<img width="484" alt="image" src="https://github.com/ShuhongChen/eisai-anime-interpolator/assets/81129278/e2765920-9f3f-4b1f-bc5b-4692b1dc0ef4">
请问这是什么原因导致的？

**Comment by ShuhongChen** [comment]
没问题，尽管问；我们的 `make/docker_pull` 是在 pull 这个 image:
https://hub.docker.com/r/shuhongchen/eisai-anime-interpolator
直接pull它行吗？可能要叫sudo

如果不行请试一下docker hub的hello world：
https://hub.docker.com/_/hello-world
helloworld 不行的话肯定是机器local的permission error

**Comment by luyiwen-user** [comment]
你好，这个镜像已经拉取下来了，但是再执行`make/shell_docker`命令时依然出现了这个错误，请问该怎么解决？
<img width="100" alt="image" src="https://github.com/ShuhongChen/eisai-anime-interpolator/assets/81129278/405db034-8bdb-45e1-ae60-5d34643c4147">
<img width="372" alt="image" src="https://github.com/ShuhongChen/eisai-anime-interpolator/assets/81129278/70a02a64-e9eb-4889-a2c4-8849e8ae3078">

**Comment by luyiwen-user** [comment]
您好，拉取镜像后，在执行`sudo make/shell_docker`报下列错误，请问该怎么解决？
<img width="744" alt="image" src="https://github.com/ShuhongChen/eisai-anime-interpolator/assets/81129278/1f29da5b-8f40-42db-ae46-f4b3a3b3f167">

**Comment by ShuhongChen** [comment]
不好意思回答晚了

为什么它在mount `.../eisai-anime-interpolator-master/_env/_env/home/.bashrc`？不因给有两个`_env`，估计是`_env/project_config.bashrc`里`PROJECT_DN`多了个`_env`
