### ISSUE TITLE
hi,my input picture's size is 1920*1080 ,and output picture is blurry

### ISSUE THREAD

**Issue by jojokic** [ShuhongChen/eisai-anime-interpolator#23]
your code is great,and i want to have Pictures with original clarity.

**Comment by ShuhongChen** [comment]
hello, thanks for your interest in our work, sorry for the delayed response

yes, it's pretty common to have blur artifacts with interpolation systems; while ours usually does better than animeinterp for example, the outputs still may be blurry

if your blurriness is coming from downsampling to fit into our system, you could try processing different parts of the image separately and then stitching them together again, though it may not help too much
