### ISSUE TITLE
Colab broken

### ISSUE THREAD

**Issue by elasticdotventures** [ShuhongChen/eisai-anime-interpolator#26]
This command fails, unable to access the gdrive file from colab or using my browser directly

gdown 1GmieiyZyUGr6Vm9mCOrK6DiqlAclby-G
https://drive.google.com/uc?id=1GmieiyZyUGr6Vm9mCOrK6DiqlAclby-G

**Comment by elasticdotventures** [comment]
after a bit of sleuthing I see there is a redirect.txt file.
Have confirmed that this works:
```
gdown 1QxS3PiyM-Vf0lj1eqlXdDvyMqXsKfBna
```

**Comment by elasticdotventures** [comment]
I've modified the colab notebook and also made it so you can upload a START_FRAME and FINISH_FRAME

https://colab.research.google.com/github/elasticdotventures/eisai-anime-interpolator/blob/colab-fixes/_notebooks/eisai_colab_demo.ipynb

**Comment by ShuhongChen** [comment]
Thanks for pointing this out, we recently had to move the folder; I committed the changed id to the ipynb
