### ISSUE TITLE
About sigma_factor and exp_factor

### ISSUE THREAD

**Issue by 98mxr** [ShuhongChen/eisai-anime-interpolator#5]
I found that `sigma_factor=1/540, exp_factor=540/15` are constants independent of h and w. Does this have anything to do with the` (540, 960) `specified in the interpolate? Please how should I modify the `sigma_factor` and `exp_factor` to fit arbitrary resolutions.

**Comment by ShuhongChen** [comment]
> constants independent of h and w

I don't think they're independent? please see [here](https://github.com/ShuhongChen/eisai-anime-interpolator/blob/350d2418a0dd42784c19cf10dfdc420406718f00/_train/frame_interpolation/models/ssldtm.py#L101) and [here](https://github.com/ShuhongChen/eisai-anime-interpolator/blob/350d2418a0dd42784c19cf10dfdc420406718f00/_train/frame_interpolation/models/ssldtm.py#L105) where both are multiplied by a function of shape

**Comment by 98mxr** [comment]
It is because of this that I have doubts. According to the sample code, then `sigma=img.shape[-2]*sigma_factor` means` sigma=1.0`, can I understand it like this?

**Comment by ShuhongChen** [comment]
> means sigma=1.0, can I understand it like this?

Yeah, I think that's right; here it means 1 pixel

**Comment by 98mxr** [comment]
So exp_factor is `(min(h, w) / 15) / max(h, w)` ?

I saw a bad area on the picture, like the picture below, changing the resolution when calculating (from 540, 960 to 960, 960) the situation changes, I've been looking for the reason.

![KHC5)$BY( ~)U4I7WQ W7 3](https://user-images.githubusercontent.com/82786769/179669738-cf1c14d4-ada8-4f89-8ae6-c408db65fb7d.jpg)
in 960x540

![U YKI8$UJ%W74($GFJ)OCBD](https://user-images.githubusercontent.com/82786769/179669803-5386f14e-8abe-4e98-bcff-63f3c3ea4e5b.jpg)
in 960x960

The source resolution is 1920x1080

Thank you very much for your replies and answers. esiai is the most powerful, performant and fast anime-vfi I've ever seen. I think now I can completely solve the vfi problem of anime as long as I overcome a little problem.

**Comment by 98mxr** [comment]
sry, I learned `exp_factor=15` from the paper.

**Comment by ShuhongChen** [comment]
> the situation changes, I've been looking for the reason

I'm assuming you mean the つ; it's hard to tell what caused this, if you find a fix here something somewhere else may break.  I'd recommend benchmark lpips/cd evaluation on atd12k instead of looking at fixing specific examples

> most powerful, performant and fast anime-vfi I've ever seen. I think now I can completely solve the vfi problem of anime

Thanks for your kind words, though I don't think anime-vfi is solved at all; the project was intended for stuff like [this](https://www.youtube.com/watch?v=VHVrvSe3myc), and we're still pretty far from this
