### ISSUE TITLE
Preprocessing the image can solve the problem of つ

### ISSUE THREAD

**Issue by routineLife1** [ShuhongChen/eisai-anime-interpolator#6]
```
img0 = img0 * 0.84 + 0.08
img1 = img1 * 0.84 + 0.08
...
out_dtm[0,:3] = (out_dtm[0,:3] - 0.08) / 0.84
```

This process will not have a significant impact on the original effect.

![NE{AEXIO0F_@46Q}37~SKI7](https://user-images.githubusercontent.com/68835291/179793736-e1a58fe1-422c-4c7d-a0fd-59dec135fe86.jpg)
![T~~1 V0MLBPW8$SE_3PXT)D](https://user-images.githubusercontent.com/68835291/179793746-97cf3628-8c45-42a0-bdb2-11d2cc4b2307.png)

**Comment by ShuhongChen** [comment]
Thanks for pointing this out; this is pretty interesting.  I know the flow estimator has problems with completely solid-color, especially white and black; I think your solution is simple and might work well

How does this affect the atd12k evaluation benchmark?  I think pure white/black screens are out-of-distribution in atd12k so this fix may actually hurt performance

This might be more atd12k's fault; the atd12k test set is limited in a lot of ways (not just missing cases like this, but also being low-quality with lots of jpeg artifacts and tv watermarks)

In any case if you run the benchmark please let us know how it goes

**Comment by 98mxr** [comment]
A year ago, I used RAFT's raft-sintel model to calculate the flow of anime a lot. At 720P resolution, after visualizing the flow, everything seems to be normal. Based on this work, I insist that the RAFT (or RFR) network is not incapable of adapting to solid-color scenes, and maybe we can think about some methods from data augmentation or optical flow GT supervision.

**Comment by ShuhongChen** [comment]
> I insist that the RAFT (or RFR) network is not incapable of adapting to solid-color scenes
> data augmentation or optical flow GT supervision

Yes I agree and think you're correct; I'm saying above that even if we fix solid-color problems, the improvement might not show up when you benchmark the fix on atd12k; a better benchmark than atd12k might be needed to observe performance increase

**Comment by splinter21** [comment]
> > I insist that the RAFT (or RFR) network is not incapable of adapting to solid-color scenes
> > data augmentation or optical flow GT supervision
> 
> Yes I agree and think you're correct; I'm saying above that even if we fix solid-color problems, the improvement might not show up when you benchmark the fix on atd12k; a better benchmark than atd12k might be needed to observe performance increase

他说non-0.5的意思是，实际需求不局限于补中间时刻，而是补任意时间点，然而测试集并没有这种好东西给作为参考帧算PSNR

**Comment by ShuhongChen** [comment]
> 他说non-0.5的意思是，实际需求不局限于补中间时刻，而是补任意时间点，然而测试集并没有这种好东西给作为参考帧算PSNR

你这回答是关于另外个[issue](https://github.com/ShuhongChen/eisai-anime-interpolator/issues/8)把？

我的意思是理解`img0 * 0.84 + 0.08`等等的影响；虽然ATD是没有non-0.5中间帧，这样的改变还会有差别

我估计的是因为ATD test里面没有他指的空白帧，他的修改可能反而破坏performance

但提出的修复建议还得用benchmark来证明有进步；问题是ATD test不是个非常好的benchmark，希望人家能用RRLD出个跟好的standard（作为我们大学来说releasing data非常困难）

**Comment by routineLife1** [comment]
releasing data涉及到版权问题么

**Comment by ShuhongChen** [comment]
是的我们胆子没 animeinterp authors 那么大；他们连 disney 都敢用

**Comment by routineLife1** [comment]
有试过自己准备的数据集训练么，视觉效果有提升么

**Comment by ShuhongChen** [comment]
没有，当时只加9k samples为了缩短training缩小diskspace（SGM flows太贵得precompute），从此没时间再增加...

**Comment by routineLife1** [comment]
SGM flow的用处不大吧，以及目前似乎没有用cuda计算的方法

**Comment by ShuhongChen** [comment]
是不大，要是不在写paper的话可能就不用了

**Comment by routineLife1** [comment]
我如果私下准备数据训练的话，可以不准备SGM flows吧

**Comment by ShuhongChen** [comment]
yeah我估计performance还是会有影响，我们appendix里有这个实验

但除非你有大量compute是没法计算SGM；另外可以选择自己从写cuda SGM，但要是有这么努力可能不如找办法train更好的flowestimator（unsupervised或synthetic data）
