### ISSUE TITLE
A Little problem

### ISSUE THREAD

**Issue by routineLife1** [ShuhongChen/eisai-anime-interpolator#7]
downsample the image before calculating the optical flow and upsample the optical flow after the calculation can solve the following problems, but at the same time it will cause line jitter. Adjusting the iters of the optical flow calculation can also solve this problem (but only for frames with smaller resolutions), which will slow down the speed.

![JVA79@7~ H3EK79L4B)C DF](https://user-images.githubusercontent.com/68835291/179811403-d6062a15-7f65-4173-907c-f46d31d83f73.jpg)
![F)@2ZJFEYHTVON`36AHGW2B](https://user-images.githubusercontent.com/68835291/179811444-792fe56b-af5e-478b-acfb-a78ac9b8d737.png)

```
# wrapper
def interpolate(raft, ssl, dtm, img0, img1, ts, scale = 1.0):
    with torch.no_grad():
        img0,img1 = img0.t()[None,:3].to(device), img1.t()[None,:3].to(device)
        img0 = img0*0.84 + 0.08
        img1 = img1*0.84 + 0.08
        img0_l = F.interpolate(img0,scale_factor=scale,mode='bilinear')
        img1_l = F.interpolate(img1,scale_factor=scale,mode='bilinear')
        flow0,_ = raft(img0_l, img1_l)
        flow1,_ = raft(img1_l, img0_l)
        flow0 = F.interpolate(flow0,scale_factor=(1/scale),mode='bilinear') * (1/scale)
        flow1 = F.interpolate(flow1,scale_factor=(1/scale),mode='bilinear') * (1/scale)
        x = {
            'images': torch.stack([img0,img1], dim=1),
            'flows': torch.stack([flow0,flow1], dim=1),
        }
        out_ssl_s,_ = ssl(x, ts = ts)
        ans_ts = []
        for out_ssl in out_ssl_s:
            out_dtm = dtm(x, out_ssl, _)
            out_dtm = (out_dtm - 0.08) / 0.84
            ans_ts.append(I(out_dtm[0,:3].float().clamp(0,1).cpu()))
    return ans_ts

```
```

# raft helper
from _train.frame_interpolation.helpers.raft_v1 import rfr_new as uraft
class RAFT(nn.Module):
    def __init__(self, path='./checkpoints/anime_interp_full.ckpt'):
        super().__init__()
        self.raft = uraft.RFR(Namespace(
            small=False,
            mixed_precision=False,
        ))
        if path is not None:
            sd = torch.load(path)['model_state_dict']
            self.raft.load_state_dict({
                k[len('module.flownet.'):]: v
                for k,v in sd.items()
                if k.startswith('module.flownet.')
            }, strict=False)
        return
    def forward(self, img0, img1, flow0=None, **iters=20**, return_more=False):
        if flow0 is not None:
            flow0 = flow0.flip(dims=(1,))
        out = self.raft(img1, img0, iters=iters, flow_init=flow0)
        return out[0].flip(dims=(1,)), (locals() if return_more else None)
```

**Comment by routineLife1** [comment]
downsample the image before optical flow calculation can optimize the effect of large-scale motion interpolation，but there are still some strange pixels

![01](https://user-images.githubusercontent.com/68835291/179814463-6846c253-2b28-458d-8c1b-ff815cabcbaf.jpg)

**Comment by ShuhongChen** [comment]
Thanks for the analysis; yes, anime flow estimation is still pretty bad; we only focused on synthesis in our paper, and animeinterp's SGM is expensive without that much performance improvement

I think tricks like up/downsampling you have might make some improvement, but I think for a major advance you'd probably need to retrain, probably on synthetic data with anime-specific augmentations
