### ISSUE TITLE
Solid colors seem to create artefacts

### ISSUE THREAD

**Issue by styler00dollar** [ShuhongChen/eisai-anime-interpolator#9]
If I input 2 pure white frames I get this as a result. As a suggestion I would put in some solid color frames into training data.
![test](https://user-images.githubusercontent.com/51405565/179823339-19b46ef6-1fe2-4ac7-ade3-99bffed0feff.png)

**Comment by styler00dollar** [comment]
This seems to be also present if bigger areas are a solid color.
![1](https://user-images.githubusercontent.com/51405565/179826642-52a9d215-014e-42b2-8ffb-4ea958453bc7.png)
![2](https://user-images.githubusercontent.com/51405565/179826647-6249ec9f-7a93-490c-be06-b7928a28d433.png)
![3](https://user-images.githubusercontent.com/51405565/179826651-168ef52d-4b20-442e-98e3-e5499d6a4061.png)

**Comment by ShuhongChen** [comment]
Thanks for pointing this out; yes, blank colors are pretty out-of-distribution in atd12k and our collected set, I think white and black are particularly bad

I mentioned a bit in other post too, but atd12k is a pretty imperfect training set and benchmark (missing cases like this, compression artifacts, tv watermarks, etc.); it'd be nice if someone compiled a larger/better benchmark with RRLD and released the data, but for us as a university things get complicated with copyright

I was surprised the animeinterp authors were brave enough to release frames from disney even
